import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class NumberCounter {
    
	public int CoutnNumbers(String input) {
		int count=0;
		if(input != null){
			Pattern p= Pattern.compile("[0-9]");
			Matcher m = p.matcher(input);
			while (m.find())
			{
				count++;
			}
			return count;
		}
		else{
			System.out.println("The entered string can't be nulled");
			return 0;
		}
	}
	
	public String askForString (){
		System.out.println("Enter the string");
		Scanner sc=new Scanner(System.in);
		return sc.nextLine();
	}


    public static void main(String[] args) {
    	NumberCounter obj = new NumberCounter();
        System.out.println("There are " + obj.CoutnNumbers(obj.askForString()) + " numbers in the string");
    }
}
